import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Building2, ChevronLeft, Eye, Printer, Send, Star, Users } from 'lucide-react';
import {
  HalfStarRating, PlatformCell, RateBar, ReportDelta, ReportEmpty, ReportStatTile, SectionHeading, SkeletonRows, TableHead,
} from '../components/report/ReportParts';
import { Button, cn } from '../components/ui/Button';
import { useDealerProfile } from '../contexts/DealerProfileContext';
import { dashboardService, type DashboardStats, type DealerAnalytics } from '../services/dashboard';
import { trackEvent } from '../services/events';
import { formatDuration, monthLabel, responseRateColor } from '../utils/analytics';

const TABLE = 'rounded-xl border border-zinc-200/80 overflow-hidden';
const TILE = 'bg-white rounded-xl border border-zinc-200/80 shadow-sm p-4 print:shadow-none';

export default function ReportPage() {
  const navigate = useNavigate();
  const { profile } = useDealerProfile();
  const [now] = useState(() => new Date());
  const [stats, setStats] = useState<DashboardStats | null | undefined>(undefined); // undefined: loading, null: failed
  const [insights, setInsights] = useState<DealerAnalytics | null | undefined>(undefined);

  useEffect(() => {
    dashboardService.get().then((d) => setStats(d.stats)).catch(() => setStats(null));
    dashboardService.analytics().then(setInsights).catch(() => setInsights(null));
  }, []);

  // No PDF is generated here: "Save as PDF" is the browser's print destination.
  const print = () => {
    trackEvent('report.downloaded');
    window.print();
  };

  const statsLoading = stats === undefined;
  const sectionsLoading = insights === undefined;
  const summary = insights?.reviewSummary ?? null;
  const followers = insights?.followerTrend ?? [];
  const engagement = insights?.engagementByType ?? [];
  const maxRate = Math.max(0, ...engagement.map((r) => r.engagementRate));

  return (
    <div className="min-h-screen bg-zinc-50 print:bg-white py-8 print:py-0">
      <div className="max-w-3xl mx-auto mb-5 flex items-center justify-between print:hidden px-4 sm:px-0">
        <button type="button" onClick={() => navigate('/analytics')} className="inline-flex items-center gap-1 text-sm font-medium text-zinc-600 hover:text-zinc-900 transition-colors">
          <ChevronLeft className="w-4 h-4" />
          Back to analytics
        </button>
        <Button onClick={print}>
          <Printer className="w-4 h-4" />
          Print / Save as PDF
        </Button>
      </div>

      <div className="max-w-3xl mx-auto bg-white print:shadow-none shadow-sm rounded-2xl border border-zinc-200/80 print:rounded-none print:border-0 overflow-hidden">
        <div className="px-8 pt-8 pb-6 border-b border-zinc-100 print:px-6 flex flex-wrap items-start justify-between gap-4">
          <div className="flex items-center gap-3 min-w-0">
            {profile?.logo_url ? (
              <img src={profile.logo_url} alt="" className="w-12 h-12 rounded-xl object-contain ring-1 ring-zinc-200 bg-zinc-50 flex-shrink-0" />
            ) : (
              <div className="w-12 h-12 rounded-xl bg-orange-50 ring-1 ring-orange-100 flex items-center justify-center flex-shrink-0">
                <Building2 className="w-5 h-5 text-orange-600" />
              </div>
            )}
            <div className="min-w-0">
              <h1 className="text-xl font-semibold tracking-tight text-zinc-900 truncate">{profile?.name || 'Dealership'}</h1>
              <p className="text-sm text-zinc-500">{profile?.city ? `${profile.city} · ` : ''}Social performance report</p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-sm font-semibold text-zinc-900">{monthLabel(now)}</p>
            <p className="text-[11px] text-zinc-400">Generated by Social AI</p>
          </div>
        </div>

        <div className="px-8 py-7 space-y-8 print:px-6">
          <section>
            <SectionHeading title="Key metrics" subtitle="Month-to-date performance overview" />
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 print:grid-cols-4">
              <ReportStatTile loading={statsLoading} icon={<Send className="w-4 h-4 text-orange-600" />} accent="bg-orange-50" label="Posts published" value={stats ? String(stats.publishedThisMonth) : '—'} />
              <ReportStatTile loading={statsLoading} icon={<Eye className="w-4 h-4 text-blue-600" />} accent="bg-blue-50" label="Total reach" value={stats ? stats.reachThisMonth.toLocaleString('en-IN') : '—'} />
              <ReportStatTile loading={statsLoading} icon={<Users className="w-4 h-4 text-violet-600" />} accent="bg-violet-50" label="Leads generated" value={stats ? String(stats.leadsGenerated) : '—'} />
              <ReportStatTile
                loading={sectionsLoading}
                icon={<Star className="w-4 h-4 text-amber-500" />}
                accent="bg-amber-50"
                label="Avg. rating"
                value={summary?.avgRating == null ? '—' : `${summary.avgRating}★`}
              />
            </div>
          </section>

          <section className="print:break-inside-avoid">
            <SectionHeading title="Follower growth" subtitle="Net change over the last 30 days" />
            {!sectionsLoading && followers.length === 0 ? (
              <ReportEmpty title="No follower data captured yet" text="Data will appear once platform connections are synced." />
            ) : (
              <div className={TABLE}>
                <table className="w-full text-sm">
                  <TableHead columns={[{ label: 'Platform' }, { label: 'Followers', align: 'right' }, { label: '30-day change', align: 'right' }]} />
                  <tbody className="divide-y divide-zinc-100">
                    {sectionsLoading ? <SkeletonRows columns={3} /> : followers.map((f) => (
                      <tr key={f.platform} className="hover:bg-zinc-50/60 transition-colors">
                        <td className="py-2.5 px-4"><PlatformCell platform={f.platform} /></td>
                        <td className="py-2.5 px-4 text-right font-semibold text-zinc-900 tabular-nums">{f.current.toLocaleString('en-IN')}</td>
                        <td className="py-2.5 px-4 text-right"><ReportDelta value={f.delta} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>

          <section className="print:break-inside-avoid">
            <SectionHeading title="Engagement by post type" subtitle="Breakdown of published-post performance" />
            {!sectionsLoading && engagement.length === 0 ? (
              <ReportEmpty title="No published-post metrics yet" text="Metrics will populate after your first posts are published." />
            ) : (
              <div className={TABLE}>
                <table className="w-full text-sm">
                  <TableHead columns={[{ label: 'Type' }, { label: 'Posts', align: 'right' }, { label: 'Reach', align: 'right' }, { label: 'Eng. rate', align: 'right' }]} />
                  <tbody className="divide-y divide-zinc-100">
                    {sectionsLoading ? <SkeletonRows columns={4} /> : engagement.map((r) => (
                      <tr key={r.type} className="hover:bg-zinc-50/60 transition-colors">
                        <td className="py-2.5 px-4 font-medium text-zinc-800 capitalize">{r.type}</td>
                        <td className="py-2.5 px-4 text-right tabular-nums">{r.posts}</td>
                        <td className="py-2.5 px-4 text-right tabular-nums">{r.reach.toLocaleString('en-IN')}</td>
                        <td className="py-2.5 px-4"><RateBar rate={r.engagementRate} max={maxRate} /></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>

          <section className="print:break-inside-avoid">
            <SectionHeading title="Reviews" subtitle="Google Business Profile review metrics" />
            {sectionsLoading ? (
              <div className="grid grid-cols-3 gap-3">
                {[0, 1, 2].map((i) => (
                  <div key={i} className={TILE}>
                    <div className="h-3 w-20 bg-zinc-100 rounded animate-pulse" />
                    <div className="h-6 w-16 bg-zinc-100 rounded animate-pulse mt-2" />
                  </div>
                ))}
              </div>
            ) : (
              <div className="grid grid-cols-3 gap-3">
                <div className={TILE}>
                  <p className="text-xs text-zinc-500 font-medium">Response rate</p>
                  <p className="text-2xl font-bold tracking-tight text-zinc-900 mt-1">{summary?.responseRate == null ? '—' : `${summary.responseRate}%`}</p>
                  {summary?.responseRate != null && (
                    <div className="mt-2 h-1.5 bg-zinc-100 rounded-full overflow-hidden">
                      <div className={cn('h-full rounded-full', responseRateColor(summary.responseRate))} style={{ width: `${summary.responseRate}%` }} />
                    </div>
                  )}
                </div>
                <div className={TILE}>
                  <p className="text-xs text-zinc-500 font-medium">Total reviews</p>
                  <p className="text-2xl font-bold tracking-tight text-zinc-900 mt-1">{summary ? summary.totalReviews : '—'}</p>
                  {summary?.avgRating != null && <div className="mt-2"><HalfStarRating rating={summary.avgRating} /></div>}
                </div>
                <div className={TILE}>
                  <p className="text-xs text-zinc-500 font-medium">Avg. response time</p>
                  <p className="text-2xl font-bold tracking-tight text-zinc-900 mt-1">{formatDuration(summary?.avgResponseMinutes ?? null)}</p>
                  {summary?.avgResponseMinutes != null && <p className="text-[11px] text-zinc-400 mt-1">per review on average</p>}
                </div>
              </div>
            )}
          </section>
        </div>

        <div className="px-8 py-4 border-t border-zinc-100 bg-zinc-50/60 print:bg-white print:px-6 flex flex-wrap items-center justify-between gap-3">
          <p className="text-[11px] text-zinc-400">Auto-generated by Social AI · Share with your OEM or management team.</p>
          <span className="text-xs font-semibold text-zinc-600">Social <span className="text-orange-600">AI</span></span>
        </div>
      </div>
    </div>
  );
}
